services:
  frontend:
    image: cff:latest
    build: .
    container_name: frontend
    restart: unless-stopped
    environment:
      - "NEXT_PUBLIC_API_HOST=${CFFBackendHost}"
      - "NEXT_PUBLIC_API_PORT=${CFFBackendPort}"
    ports:
      - 3000:3000
    networks:
      - cyberfarm_backend
