
import { Inter } from "next/font/google";
import NavBar from '@/app/ui/navbar'
const inter = Inter({ subsets: ["latin"] });

export const metadata = {

  title: "Create Next App",

  description: "Generated by create next app",

};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        {/* Layout UI */}
        {/* Place children where you want to render a page or nested layout */}
        <main>
          {children}
        </main>
      </body>
    </html>
  )
}